### ISSUE TITLE
Overkill

### ISSUE THREAD

**Issue by Sekilloda** [Intellbg/30DaysOfCode#2]

**Comment by Sekilloda** [comment]
Creo que usar regex para el patrón pedido en todas las partes del reto es demasiado, con is.alpha() e is.numeric() basta y están incluidas sin importar a re, pero por supuesto esta solución se puede generalizar mucho más fácil para cualquier otro patrón y la que no importa re no. Buena documentación, estilísticamente sobria, personalmente me gusta. ¿Tal vez sería más indicado crear un test case para que lo que el usuario ingresa en la última función tiene longitud 1, en vez de tomar el primer carácter?

**Comment by Intellbg** [comment]
Confirmó que si es overkill, no se me ocurrió usar los métodos mencionados ya que retornan un valor Booleano. Sin embargo, gracias a su implementación caí en cuenta que igual podría ir sumando lo retornado ya que a la final es 0 o 1.

**Comment by Intellbg** [comment]
Confirmó que si es overkill, no se me ocurrió usar los métodos mencionados ya que retornan un valor Booleano. Sin embargo, gracias a su implementación caí en cuenta que igual podría ir sumando lo retornado ya que a la final es 0 o 1.

A lo del test case se referiría a realizar una validación con alguna especie de loop del tipo

```
user_input=input()
while len(user_input)!=1:
  print("warning message")
  user_input=input()
```

**Comment by Sekilloda** [comment]
Si, correcto, algo así.
